### ISSUE TITLE
.EXE Release?

### ISSUE THREAD

**Issue by Mongrul** [Reneator/Godot-Path-of-Oil#1]
Hey there, I was wondering if you were going to release a .exe for this. I got it to work in Godot, but cannot get it to export and run for some reason.  Love what you are doing here!

**Comment by Reneator** [comment]
Hey hey, i had some difficulties setting up the exports for the pipelines. Got windows export running but the resulting exe doesnt work properly yet. 

Gonna check that.

Thanks a lot for your feedback! <3

**Comment by Reneator** [comment]
Soo, i created a release.
Was able to fix 2 problems caused by the export specifically.

**Comment by Mongrul** [comment]
It works awesome thanks!  I will be doing some map running today, so I will let you know if I run into any issues.  The annoint's I have checked so far work!

**Comment by Reneator** [comment]
Thanks a bunch!

**Comment by meips** [comment]
How to Use:
Open tool
...

Amm who can i launch it? :S, do u have 1 exe? Thank you.

**Comment by Reneator** [comment]
Download the zip file with the appropriate naming. 
in this case its:

[Path.of.Oil.Godot.zip](https://github.com/Reneator/Godot-Path-of-Oil/releases/download/1.0.3/Path.of.Oil.Godot.zip)

(i forgot to put win in the name)
