### ISSUE TITLE
Few missing Annoints

### ISSUE THREAD

**Issue by Mongrul** [Reneator/Godot-Path-of-Oil#2]
Hello again, I have found a few annoints that are not working

High Voltage
Steeped in the Profane

Thanks!

**Comment by Mongrul** [comment]
Found another

Overprepared

**Comment by Reneator** [comment]
Hey mate,
thanks for the Info!

Seems like those arent yet added to the list of anointments on the wiki and overprepared has an old name in the wiki.

I added all 3 and going to create a release (trying to add the "create release" step to the pipeline, so its even easier to deploy)

Keep it up!

**Comment by Mongrul** [comment]
Sounds good! If I run into anymore Ill report it.  Keep up the good work this tool is amazing for time savings.

**Comment by Reneator** [comment]
Thanks a lot for your input!
Keep it up!
