### ISSUE TITLE
1.0.1 Windows version issue

### ISSUE THREAD

**Issue by Mongrul** [Reneator/Godot-Path-of-Oil#3]
Hey there, I cant get the new version to download. It keeps calling it a Virus.  I have no problem downloading version 1.0.0.

Thanks!

**Comment by Reneator** [comment]
Thanks for the info, going to check it out.

At what step does it tell you that? at the moment you download it? or after opening the zip?

**Comment by Reneator** [comment]
Ah, tried downloading the 1.0 version and it also says "cancelled virus detected" for me, dang.

**Comment by Reneator** [comment]
Maybe some recent windows or browser update changed the detection? 🤔

**Comment by Reneator** [comment]
Replaced the 1.0.1 windows zip with a version i created locally, but it is still saying "virus detected" on download. Gonna try if signing the code helps (gotta check out how to do it)

**Comment by Reneator** [comment]
Hmm weird.

**Comment by Reneator** [comment]
Ah, added the .exe directly, without wrapping it in a zip and it worked for me.

**Comment by Mongrul** [comment]
That worked! Thanks!
