### ISSUE TITLE
Annoints not showing

### ISSUE THREAD

**Issue by Skryze** [Reneator/Godot-Path-of-Oil#5]
Is it just me or aren't the annoints showing up anymore on 3.21 Crucible? Checked it out by hovering over two Amulets. One with Nightstalker (Sepia, Teal, Gold) and Arsonist (Verdant, Verdant, Azure). 

Edit: Playing on Windows. Patch 3.21.0c
![bug](https://user-images.githubusercontent.com/125007960/232251509-f1f9da68-dec7-4bf5-9973-f33fccfe5b43.png)

**Comment by Reneator** [comment]
Hey mate, thanks a lot for reporting. Could you send me the clipboard for the amulet? Im currently not that far into the game yet, so i dont have many items with annoints yet.

**Comment by Reneator** [comment]
Just checked the list and both seem to be still there, maybe there is something else going wrong.

Is it working for other items for you? Is it working with other annoints on amulets or amulets in general arent working?

**Comment by Reneator** [comment]
Just looking at the window again, it seems the program was struggling to get started (the inside should be a lighter gray)

**Comment by Reneator** [comment]
Migrated the tool to godot 4 and new release is out, could you test it again with the new release?

**Comment by Skryze** [comment]
Thank you for the quick reply. Just downloaded the new version. I have a stash tab with a bunch of anointed amulets and rings and still none of them show any oils. 

Edit: I am playing the game in windowed fullscreen (borderless) as you probably should when you are using overlays, right? 

Edit II: Just restarted my computer without any other overlays running except for the Godot-Path-Of-Oil and still won't show me any Oil's while hovering over different anointed items.

**Comment by Reneator** [comment]
Are you just hovering or are you pressing CTRL+C when hovering over an item?

The tool uses the item-info that gets printed to the clipboard by PoE when pressing CTRL+C over an item. (similar to what craftofExile uses)

**Comment by Skryze** [comment]
Well that explains it. It works. Now I feel kind of dumb lmao. Thank you for taking your time to update your tool and helping me out.
Would suggest creating a readme for your repo with this shortcut in case someone else gets stuck on the same thing as well.

**Comment by Reneator** [comment]
No Problem, Thanks for taking your time as well!

That is a good point, i will do that!

Keep it up!

**Comment by Reneator** [comment]
Added a Readme!
